# Author(s) : Conor Cowley
from antlr4 import InputStream, CommonTokenStream

from algorithm.Preprocessors.Preprocessor import Preprocessor
from algorithm.Parsers.JavaParser.JavaLexer import JavaLexer
from algorithm.Parsers.JavaParser.JavaParser import JavaParser

from algorithm.Parsers.JavaParser.JavaParserVisitor import JavaParserVisitor
# PREPROCESSOR FOR JAVA
class JavaPreprocessor(Preprocessor):
    
    #The `preprocessCode` method removes preprocessor directives from code, as well as unnecessary characters.
    def preprocess(self):
        lexer = JavaLexer(InputStream(self.file))
        stream = CommonTokenStream(lexer) # stream of common tokens are generated.
        parser = JavaParser(stream) #Generate a parser which uses the common stream of tokens generated by the lexer.
        self.tree = parser.compilationUnit()
        self.removeTreeNoise()
        self.processed_str = self.tree.getText()

    #The `removeTreeNoise` function aims to remove unnecessary noise such as print statements that could potentially impact the accuracy of the algorithm.
    def removeTreeNoise(self):
        #This may be needed if ANTLR cannot remove the noise for us.
        visitor = JavaParserVisitor()
        
        visitor.visit(self.tree)
        
        pass
